# Generated by Django 5.2 on 2025-08-20 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_skills_skill_alter_skills_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['position'], 'verbose_name': 'Изображение', 'verbose_name_plural': 'Галерея'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата приема'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tester',
            field=models.BooleanField(default=False, verbose_name='Тестировщик'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='position',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='level',
            field=models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], verbose_name='Уровень освоения'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.SmallIntegerField(choices=[(0, 'не указан'), (1, 'мужской'), (2, 'женский')], default=0, verbose_name='Пол'),
        ),
    ]
